services:
  db:
    image: postgres:14
    platform: ${TARGETPLATFORM:-linux/amd64}
    container_name: healthcheck-db
    environment:
      POSTGRES_DB: healthcheck
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - backend
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d healthcheck"]
      interval: 10s
      timeout: 5s
      retries: 5

  api:
    build: ./api
    platform: ${TARGETPLATFORM:-linux/amd64}
    container_name: healthcheck-api
    environment:
      DATABASE_URL: postgresql://user:password@db:5432/healthcheck
    ports:
      - "8000:8000"
    networks:
      - backend
      - frontend
    depends_on:
      db:
        condition: service_healthy
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8000/health || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    restart: always

  client:
    build: ./client
    platform: ${TARGETPLATFORM:-linux/amd64}
    container_name: healthcheck-client
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_API_URL=http://api:8000
    ports:
      - "3000:3000"
    networks:
      - frontend
    depends_on:
      api:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "node", "-e", "require('http').get('http://localhost:3000', (r) => r.statusCode === 200 ? process.exit(0) : process.exit(1))"]
      interval: 30s
      timeout: 20s
      retries: 5
      start_period: 90s
    deploy:
      resources:
        limits:
          memory: 4G
        reservations:
          memory: 2G
    restart: unless-stopped

  proxy:
    build: ./proxy
    container_name: healthcheck-proxy
    ports:
      - "80:80"
    depends_on:
      - api
      - monitor
      - client
    networks:
      - frontend
      - backend
    restart: unless-stopped

  monitor:
    build: ./monitor
    container_name: healthcheck-monitor
    ports:
      - "3001:3001"
    networks:
      - frontend
      - backend
    restart: unless-stopped

networks:
  frontend:
    name: healthcheck-frontend
  backend:
    name: healthcheck-backend

volumes:
  db_data:
    name: healthcheck-db-data
  nginx_logs:
    name: healthcheck-nginx-logs
