name: Docker Publish

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  REGISTRY: ghcr.io

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Log in to the Container registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push API image
        uses: docker/build-push-action@v4
        with:
          context: ./api
          push: true
          tags: ${{ env.REGISTRY }}/${{ github.repository }}/api:latest

      - name: Build and push Client image
        uses: docker/build-push-action@v4
        with:
          context: ./client
          push: true
          tags: ${{ env.REGISTRY }}/${{ github.repository }}/client:latest

      - name: Build and push Proxy image
        uses: docker/build-push-action@v4
        with:
          context: ./proxy
          push: true
          tags: ${{ env.REGISTRY }}/${{ github.repository }}/proxy:latest

      - name: Build and push DB image
        uses: docker/build-push-action@v4
        with:
          context: ./db
          push: true
          tags: ${{ env.REGISTRY }}/${{ github.repository }}/db:latest

      - name: Build and push Monitor image
        uses: docker/build-push-action@v4
        with:
          context: ./monitor
          push: true
          tags: ${{ env.REGISTRY }}/${{ github.repository }}/monitor:latest
